config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'forecast#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :user_cities, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  def self.search(name)
    if name
      city = find_by(name: name)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :user_cities, -> { joins(:city).includes(:city)}, dependent: :destroy
  has_many :cities, through: :user_cities

  validates :email, presence: true, uniqueness: true
end

app/models/user_city.rb
class UserCity < ApplicationRecord
  belongs_to :user
  belongs_to :city

  validates :user_id, uniqueness: { scope: :city_id, message: 'City for this user already exist' }
  validates :uid, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/forecast_controller.rb
class ForecastController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    auth = Authentication.new(params)
    if auth.authenticated?
      session[:user_id] = auth.user.id
      redirect_to root_url, notice: 'You have logged in successfully'
    else
      flash.now.alert = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'You have logged out successfully'
  end
end

app/controllers/user_cities_controller.rb
class UserCitiesController < ApplicationController
  def show
    city = UserCity.find(params[:id]).city
    @forecast = ForecastService.new(city)
  end

  def new
    city = City.search(params[:search]) if params[:search]
    @forecast = ForecastService.new(city) if city
  end

  def create
    user_city = current_user.user_cities.new(user_city_params)
    if user_city.save
      redirect_to root_url, notice: "You have added #{user_city.city.name} to you cities list"
    else
      flash.now.alert = "Something went wrong. City not added"
      render 'new'
    end
  end

  private

  def user_city_params
    params.require(:user_city).permit(:uid, :city_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'You have signed up successfully'
    else
      render 'new'
    end
  end

  def destroy
    user = User.find(params[:id])
    session[:user_id] = @current_user = nil
    user.destroy
    redirect_to root_url, notice: 'You have deleted your account'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecast_helper.rb
module ForecastHelper
  def city_tile(user_city)
    raw("
      <div class='col-md-2 city-link' style='background: #{random_color}'>
        <div class='city-tile-city-name'>
          #{user_city.city.name}
        </div>
      </div>
    ")
  end

  def random_color
    colors = %w[#ff1919 #ff8919 #a492aa #15d315 #2158b4 #ffad19 #3e28bb #ffd019 #6e1eb7 #fff419 #c0139f #c4f518]
    colors.shuffle.pop
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_cities_helper.rb
module UserCitiesHelper
  def to_celsius(temp)
    (temp - 273).round
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forecast/_forecast.html.haml
%table.table.table-striped
  %tr
    %th Hour and Day
    %th Weather
    %th Temperature
    %th Air pressure
    %th Air humidity
    %th Wind speed

  - @forecast.response[:list].each do |fc|
    %tr
      %td= fc[:dt_txt]
      %td= fc[:weather][0][:description]
      %td= to_celsius(fc[:main][:temp])
      %td= fc[:main][:pressure]
      %td= fc[:main][:humidity]
      %td= fc[:wind][:speed]

app/views/forecast/index.html.haml
%h1 Welcome to Weatheroo

- if current_user
  %p Here is the forecast for authenticated users

  %p= link_to 'Search your city', new_user_city_path, class: 'btn btn-primary search-your-city-button'

  .col-md-8.col-md-offset-2
  - current_user.user_cities.each do |user_city|
    = link_to city_tile(user_city), user_city_path(user_city)

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Weatheroo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-inverse
      .container
        .navbar-brand= link_to 'Weatheroo', root_path

        - if current_user
          %ul.nav.navbar-nav.navbar-right
            %li
              %span Logged in as
              %span= current_user.email
            %li= link_to 'Log Out', logout_path
            %li= link_to 'Delete Account', user_path(current_user), method: :delete
        - else
          %ul.nav.navbar-nav.navbar-right
            %li= link_to 'Join', signup_path
            %li= link_to 'Log In', login_path


    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: 'alert alert-info'

      = yield

  = debug(params) if Rails.env.development?

app/views/user_cities/new.html.haml
%form
  .row
    .col-md-10.col-md-offset-1.search-city-form
      %h3 Find your city:
      = form_tag new_user_city_path, method: :get do
        %p.input-group
          %span.name-field
            = text_field_tag :search, params[:search], class: 'form-control'
          %span.search-submit
            = submit_tag 'Search', class: 'btn btn-sm btn-primary'

      - if @forecast
        = form_tag user_cities_path, method: :post do
          = hidden_field_tag 'user_city[city_id]', @forecast.city_id
          = hidden_field_tag 'user_city[uid]', @forecast.city_uid
          = submit_tag 'Add to your cities', class: 'btn btn-primary btn-sm'

        %h4 5 day forecast for:
        %h2= @forecast.city_name

        = render 'forecast/forecast'
        
      - else
        %h3 No Cities found

app/views/user_cities/show.html.haml
%h4 5 day forecast for:
%h2= @forecast.city_name
= render 'forecast/forecast'

app/views/users/new.html.haml
%h1 Sign up

.registration
  = form_for @user do |f|
    - if @user.errors.any?
      .error_messages
        %ul
          - @user.errors.full_messages.each do |msg|
            %li= msg

    .email-field
      = f.label :email
      %br
      = f.text_field :email

    .password-field
      = f.label :password
      %br
      = f.password_field :password

    .password-confirmation-field
      = f.label :password_confirmation
      %br
      = f.password_field :password_confirmation

    .signup-submit
      = f.submit 'Sign Up'